title: PRIMORDIAL
description: Two colonies. One battle. Your only weapon is plain English.
theme: jekyll-theme-cayman
play_url: https://primordial.thomasdvornik.com

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
